# Generated by Django 3.0.2 on 2020-03-01 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200229_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umuryango',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.District'),
        ),
    ]
