# Generated by Django 3.0.2 on 2020-03-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200301_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umuryango',
            name='district',
            field=models.CharField(choices=[(5, 'GASABO'), (6, 'GASABO')], default=5, max_length=50),
        ),
    ]
